# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1495631578);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1495631698);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1495649218);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1495631458);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1495631338);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.blocked", "{\"R1Ag65zObAlmrz1IV3ScUQ==\":1,\"ISLFZW2j2G13wI969IwCaA==\":1}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150224161057");
user_pref("browser.slowStartup.averageTime", 9555);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20150224161057");
user_pref("browser.startup.homepage_override.mstone", "31.5.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1495570526374");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1495645825514");
user_pref("datareporting.policy.firstRunTime", "1495484126374");
user_pref("datareporting.sessions.current.activeTicks", 6);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2771);
user_pref("datareporting.sessions.current.main", 671);
user_pref("datareporting.sessions.current.sessionRestored", 3225);
user_pref("datareporting.sessions.current.startTime", "1495649384374");
user_pref("datareporting.sessions.current.totalTime", 40);
user_pref("datareporting.sessions.currentIndex", 7);
user_pref("datareporting.sessions.previous.0", "{\"s\":1495484114426,\"a\":1,\"t\":705,\"c\":true,\"m\":1907,\"fp\":15875,\"sr\":16206}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1495485758809,\"a\":28,\"t\":166,\"c\":true,\"m\":883,\"fp\":8587,\"sr\":8822}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1495485929625,\"a\":55,\"t\":453,\"c\":true,\"m\":248,\"fp\":1554,\"sr\":2107}");
user_pref("datareporting.sessions.previous.3", "{\"s\":1495631042743,\"a\":0,\"t\":35,\"c\":true,\"m\":551,\"fp\":9087,\"sr\":9710}");
user_pref("datareporting.sessions.previous.4", "{\"s\":1495631097044,\"a\":1,\"t\":630,\"c\":true,\"m\":416,\"fp\":2092,\"sr\":2672}");
user_pref("datareporting.sessions.previous.5", "{\"s\":1495632396611,\"a\":71,\"t\":13342,\"c\":true,\"m\":2323,\"fp\":11698,\"sr\":12256}");
user_pref("datareporting.sessions.previous.6", "{\"s\":1495645750277,\"a\":26,\"t\":3627,\"c\":true,\"m\":733,\"fp\":13674,\"sr\":14264}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 3);
user_pref("extensions.blocklist.pingCountVersion", 3);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.5.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1494940895000,\"rdfTime\":1424819363000}}}]");
user_pref("extensions.lastAppVersion", "31.5.0");
user_pref("extensions.lastPlatformVersion", "31.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("gecko.buildID", "20150224161057");
user_pref("gecko.mstone", "31.5.0");
user_pref("idle.lastDailyNotification", 1495631287);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1495484321);
user_pref("places.history.expiration.transient_current_max_pages", 26040);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1495484321);
user_pref("toolkit.startup.last_success", 1495649385);
user_pref("toolkit.telemetry.previousBuildID", "20150224161057");
